CREATE DATABASE TraineeDb;
GO
USE TraineeDb;
GO

CREATE TABLE Countries (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Ports (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    CountryId INT NOT NULL
      FOREIGN KEY REFERENCES Countries(Id)
);

CREATE TABLE Ships (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    MaxSpeed FLOAT NOT NULL
);

CREATE TABLE Voyages (
    Id INT PRIMARY KEY IDENTITY,
    ShipId INT NOT NULL FOREIGN KEY REFERENCES Ships(Id),
    DeparturePortId INT NOT NULL FOREIGN KEY REFERENCES Ports(Id),
    ArrivalPortId INT NOT NULL FOREIGN KEY REFERENCES Ports(Id),
    StartDate DATETIME2 NOT NULL,
    EndDate   DATETIME2 NOT NULL
);